spring:
    application:
        name: customers-ms
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
            bindings:
                salesCustomerRequest-in-0:
                    destination: sales-customers-events
                    group: sales-customers-service-group
server:
    port: 8083